import json

data = {"words": [
  {"section": "1. Look-alike traps"},
  {"num": 1, "word": "ripe", "ipa": "/raɪp/", "chinese": "成熟的（水果）", "svg": ""},
  {"num": 2, "word": "rape", "ipa": "/reɪp/", "chinese": "强奸；油菜", "svg": ""},
  {"num": 3, "word": "desert", "ipa": "/ˈdezət/", "chinese": "沙漠；抛弃", "svg": ""},
  {"num": 4, "word": "dessert", "ipa": "/dɪˈzɜːt/", "chinese": "甜点", "svg": ""},
  {"num": 5, "word": "quiet", "ipa": "/ˈkwaɪət/", "chinese": "安静的", "svg": ""},
  {"num": 6, "word": "quite", "ipa": "/kwaɪt/", "chinese": "相当；完全", "svg": ""},
  {"num": 7, "word": "quit", "ipa": "/kwɪt/", "chinese": "退出；戒掉", "svg": ""},
  {"num": 8, "word": "affect", "ipa": "/əˈfekt/", "chinese": "影响（动词）", "svg": ""},
  {"num": 9, "word": "effect", "ipa": "/ɪˈfekt/", "chinese": "效果；影响（名词）", "svg": ""},
  {"num": 10, "word": "accept", "ipa": "/əkˈsept/", "chinese": "接受", "svg": ""},
  {"num": 11, "word": "except", "ipa": "/ɪkˈsept/", "chinese": "除了", "svg": ""},
  {"num": 12, "word": "adapt", "ipa": "/əˈdæpt/", "chinese": "适应；改编", "svg": ""},
  {"num": 13, "word": "adopt", "ipa": "/əˈdɒpt/", "chinese": "收养；采用", "svg": ""},
  {"num": 14, "word": "advice", "ipa": "/ədˈvaɪs/", "chinese": "建议（名词）", "svg": ""},
  {"num": 15, "word": "advise", "ipa": "/ədˈvaɪz/", "chinese": "建议（动词）", "svg": ""},
  {"num": 16, "word": "loose", "ipa": "/luːs/", "chinese": "松的；宽松的", "svg": ""},
  {"num": 17, "word": "lose", "ipa": "/luːz/", "chinese": "丢失；失去", "svg": ""},
  {"num": 18, "word": "chose", "ipa": "/tʃəʊz/", "chinese": "选择了（过去式）", "svg": ""},
  {"num": 19, "word": "choose", "ipa": "/tʃuːz/", "chinese": "选择（现在式）", "svg": ""},
  {"num": 20, "word": "cloth", "ipa": "/klɒθ/", "chinese": "布料；布", "svg": ""},
  {"num": 21, "word": "clothe", "ipa": "/kləʊð/", "chinese": "给……穿衣", "svg": ""},
  {"num": 22, "word": "clothes", "ipa": "/kləʊðz/", "chinese": "衣服", "svg": ""},
  {"num": 23, "word": "breath", "ipa": "/breθ/", "chinese": "呼吸（名词）", "svg": ""},
  {"num": 24, "word": "breathe", "ipa": "/briːð/", "chinese": "呼吸（动词）", "svg": ""},
  {"num": 25, "word": "bath", "ipa": "/bɑːθ/", "chinese": "洗澡（名词）", "svg": ""},
  {"num": 26, "word": "bathe", "ipa": "/beɪð/", "chinese": "洗澡（动词）", "svg": ""},
  {"num": 27, "word": "later", "ipa": "/ˈleɪtə/", "chinese": "之后；稍后", "svg": ""},
  {"num": 28, "word": "latter", "ipa": "/ˈlætə/", "chinese": "后者", "svg": ""},
  {"num": 29, "word": "farther", "ipa": "/ˈfɑːðə/", "chinese": "更远（距离）", "svg": ""},
  {"num": 30, "word": "further", "ipa": "/ˈfɜːðə/", "chinese": "更进一步；此外", "svg": ""},
  {"num": 31, "word": "principal", "ipa": "/ˈprɪnsɪpəl/", "chinese": "校长；主要的", "svg": ""},
  {"num": 32, "word": "principle", "ipa": "/ˈprɪnsɪpəl/", "chinese": "原则；原理", "svg": ""},
  {"num": 33, "word": "complement", "ipa": "/ˈkɒmplɪmənt/", "chinese": "补充；互补", "svg": ""},
  {"num": 34, "word": "compliment", "ipa": "/ˈkɒmplɪmənt/", "chinese": "称赞；恭维", "svg": ""},
  {"num": 35, "word": "precede", "ipa": "/prɪˈsiːd/", "chinese": "在……之前", "svg": ""},
  {"num": 36, "word": "proceed", "ipa": "/prəˈsiːd/", "chinese": "继续进行", "svg": ""},
  {"num": 37, "word": "conscious", "ipa": "/ˈkɒnʃəs/", "chinese": "有意识的；清醒的", "svg": ""},
  {"num": 38, "word": "conscience", "ipa": "/ˈkɒnʃəns/", "chinese": "良心；道德感", "svg": ""},
  {"num": 39, "word": "continual", "ipa": "/kənˈtɪnjuəl/", "chinese": "频繁的（间歇重复）", "svg": ""},
  {"num": 40, "word": "continuous", "ipa": "/kənˈtɪnjuəs/", "chinese": "持续不断的", "svg": ""},
  {"num": 41, "word": "discreet", "ipa": "/dɪˈskriːt/", "chinese": "谨慎的；不张扬的", "svg": ""},
  {"num": 42, "word": "discrete", "ipa": "/dɪˈskriːt/", "chinese": "分离的；各自独立的", "svg": ""},
  {"num": 43, "word": "elicit", "ipa": "/ɪˈlɪsɪt/", "chinese": "引出；诱出", "svg": ""},
  {"num": 44, "word": "illicit", "ipa": "/ɪˈlɪsɪt/", "chinese": "违禁的；非法的", "svg": ""},
  {"num": 45, "word": "eminent", "ipa": "/ˈemɪnənt/", "chinese": "著名的；卓越的", "svg": ""},
  {"num": 46, "word": "imminent", "ipa": "/ˈɪmɪnənt/", "chinese": "即将发生的", "svg": ""},
  {"num": 47, "word": "ensure", "ipa": "/ɪnˈʃɔː/", "chinese": "确保", "svg": ""},
  {"num": 48, "word": "insure", "ipa": "/ɪnˈʃɔː/", "chinese": "给……投保", "svg": ""},
  {"num": 49, "word": "assure", "ipa": "/əˈʃɔː/", "chinese": "向……保证", "svg": ""},
  {"num": 50, "word": "historic", "ipa": "/hɪˈstɒrɪk/", "chinese": "有历史意义的", "svg": ""},
  {"num": 51, "word": "historical", "ipa": "/hɪˈstɒrɪkəl/", "chinese": "历史上的；关于历史的", "svg": ""},
  {"num": 52, "word": "imply", "ipa": "/ɪmˈplaɪ/", "chinese": "暗示（说话者暗示）", "svg": ""},
  {"num": 53, "word": "infer", "ipa": "/ɪnˈfɜː/", "chinese": "推断（听者推断）", "svg": ""},
  {"num": 54, "word": "lay", "ipa": "/leɪ/", "chinese": "放置（及物）", "svg": ""},
  {"num": 55, "word": "lie", "ipa": "/laɪ/", "chinese": "躺；撒谎（不及物）", "svg": ""},
  {"num": 56, "word": "lend", "ipa": "/lend/", "chinese": "借给（借出）", "svg": ""},
  {"num": 57, "word": "borrow", "ipa": "/ˈbɒrəʊ/", "chinese": "借用（借入）", "svg": ""},
  {"num": 58, "word": "licence", "ipa": "/ˈlaɪsəns/", "chinese": "许可证（名词）", "svg": ""},
  {"num": 59, "word": "license", "ipa": "/ˈlaɪsəns/", "chinese": "批准；许可（动词）", "svg": ""},
  {"num": 60, "word": "practice", "ipa": "/ˈpræktɪs/", "chinese": "练习；实践（名词）", "svg": ""},
  {"num": 61, "word": "practise", "ipa": "/ˈpræktɪs/", "chinese": "练习（动词）", "svg": ""},
  {"num": 62, "word": "stationary", "ipa": "/ˈsteɪʃənəri/", "chinese": "静止不动的", "svg": ""},
  {"num": 63, "word": "stationery", "ipa": "/ˈsteɪʃənəri/", "chinese": "文具", "svg": ""},
  {"num": 64, "word": "ingenious", "ipa": "/ɪnˈdʒiːniəs/", "chinese": "聪明的；独创的", "svg": ""},
  {"num": 65, "word": "ingenuous", "ipa": "/ɪnˈdʒenjuəs/", "chinese": "天真的；坦诚的", "svg": ""},
  {"num": 66, "word": "sensual", "ipa": "/ˈsenʃuəl/", "chinese": "感官享受的；肉欲的", "svg": ""},
  {"num": 67, "word": "sensuous", "ipa": "/ˈsenʃuəs/", "chinese": "诉诸感官的；唯美的", "svg": ""},
  {"num": 68, "word": "persecute", "ipa": "/ˈpɜːsɪkjuːt/", "chinese": "迫害", "svg": ""},
  {"num": 69, "word": "prosecute", "ipa": "/ˈprɒsɪkjuːt/", "chinese": "起诉；检举", "svg": ""},

  {"section": "2. Sound-alike pairs (homophones)"},
  {"num": 70, "word": "their", "ipa": "/ðeə/", "chinese": "他们的", "svg": ""},
  {"num": 71, "word": "there", "ipa": "/ðeə/", "chinese": "在那里", "svg": ""},
  {"num": 72, "word": "they're", "ipa": "/ðeə/", "chinese": "他们是（they are）", "svg": ""},
  {"num": 73, "word": "to", "ipa": "/tuː/", "chinese": "到；向", "svg": ""},
  {"num": 74, "word": "too", "ipa": "/tuː/", "chinese": "也；太", "svg": ""},
  {"num": 75, "word": "two", "ipa": "/tuː/", "chinese": "二", "svg": ""},
  {"num": 76, "word": "your", "ipa": "/jɔː/", "chinese": "你的", "svg": ""},
  {"num": 77, "word": "you're", "ipa": "/jɔː/", "chinese": "你是（you are）", "svg": ""},
  {"num": 78, "word": "its", "ipa": "/ɪts/", "chinese": "它的", "svg": ""},
  {"num": 79, "word": "it's", "ipa": "/ɪts/", "chinese": "它是（it is）", "svg": ""},
  {"num": 80, "word": "whose", "ipa": "/huːz/", "chinese": "谁的", "svg": ""},
  {"num": 81, "word": "who's", "ipa": "/huːz/", "chinese": "谁是（who is）", "svg": ""},
  {"num": 82, "word": "here", "ipa": "/hɪə/", "chinese": "这里", "svg": ""},
  {"num": 83, "word": "hear", "ipa": "/hɪə/", "chinese": "听到", "svg": ""},
  {"num": 84, "word": "weather", "ipa": "/ˈweðə/", "chinese": "天气", "svg": ""},
  {"num": 85, "word": "whether", "ipa": "/ˈweðə/", "chinese": "是否", "svg": ""},
  {"num": 86, "word": "wear", "ipa": "/weə/", "chinese": "穿；戴", "svg": ""},
  {"num": 87, "word": "where", "ipa": "/weə/", "chinese": "在哪里", "svg": ""},
  {"num": 88, "word": "ware", "ipa": "/weə/", "chinese": "商品；器皿", "svg": ""},
  {"num": 89, "word": "meat", "ipa": "/miːt/", "chinese": "肉", "svg": ""},
  {"num": 90, "word": "meet", "ipa": "/miːt/", "chinese": "见面", "svg": ""},
  {"num": 91, "word": "week", "ipa": "/wiːk/", "chinese": "周；星期", "svg": ""},
  {"num": 92, "word": "weak", "ipa": "/wiːk/", "chinese": "虚弱的", "svg": ""},
  {"num": 93, "word": "peace", "ipa": "/piːs/", "chinese": "和平", "svg": ""},
  {"num": 94, "word": "piece", "ipa": "/piːs/", "chinese": "一片；一块", "svg": ""},
  {"num": 95, "word": "seam", "ipa": "/siːm/", "chinese": "缝合处；接缝", "svg": ""},
  {"num": 96, "word": "seem", "ipa": "/siːm/", "chinese": "似乎；好像", "svg": ""},
  {"num": 97, "word": "bear", "ipa": "/beə/", "chinese": "熊；承受", "svg": ""},
  {"num": 98, "word": "bare", "ipa": "/beə/", "chinese": "裸露的；光秃的", "svg": ""},
  {"num": 99, "word": "hair", "ipa": "/heə/", "chinese": "头发", "svg": ""},
  {"num": 100, "word": "hare", "ipa": "/heə/", "chinese": "野兔", "svg": ""},
  {"num": 101, "word": "pear", "ipa": "/peə/", "chinese": "梨", "svg": ""},
  {"num": 102, "word": "pair", "ipa": "/peə/", "chinese": "一对；一双", "svg": ""},
  {"num": 103, "word": "pare", "ipa": "/peə/", "chinese": "削皮；削减", "svg": ""},
  {"num": 104, "word": "flour", "ipa": "/flaʊə/", "chinese": "面粉", "svg": ""},
  {"num": 105, "word": "flower", "ipa": "/flaʊə/", "chinese": "花", "svg": ""},
  {"num": 106, "word": "council", "ipa": "/ˈkaʊnsəl/", "chinese": "议会；委员会", "svg": ""},
  {"num": 107, "word": "counsel", "ipa": "/ˈkaʊnsəl/", "chinese": "建议；辅导；律师", "svg": ""},
  {"num": 108, "word": "site", "ipa": "/saɪt/", "chinese": "地点；网站", "svg": ""},
  {"num": 109, "word": "sight", "ipa": "/saɪt/", "chinese": "视力；景象", "svg": ""},
  {"num": 110, "word": "cite", "ipa": "/saɪt/", "chinese": "引用；传唤", "svg": ""},
  {"num": 111, "word": "knot", "ipa": "/nɒt/", "chinese": "结；节（速度单位）", "svg": ""},
  {"num": 112, "word": "not", "ipa": "/nɒt/", "chinese": "不；没有", "svg": ""},
  {"num": 113, "word": "knight", "ipa": "/naɪt/", "chinese": "骑士", "svg": ""},
  {"num": 114, "word": "night", "ipa": "/naɪt/", "chinese": "夜晚", "svg": ""},
  {"num": 115, "word": "right", "ipa": "/raɪt/", "chinese": "右边；正确的；权利", "svg": ""},
  {"num": 116, "word": "write", "ipa": "/raɪt/", "chinese": "写", "svg": ""},
  {"num": 117, "word": "rite", "ipa": "/raɪt/", "chinese": "仪式；典礼", "svg": ""},
  {"num": 118, "word": "wright", "ipa": "/raɪt/", "chinese": "工匠（如playwright）", "svg": ""},
  {"num": 119, "word": "brake", "ipa": "/breɪk/", "chinese": "刹车", "svg": ""},
  {"num": 120, "word": "break", "ipa": "/breɪk/", "chinese": "打破；休息", "svg": ""},
  {"num": 121, "word": "steak", "ipa": "/steɪk/", "chinese": "牛排", "svg": ""},
  {"num": 122, "word": "stake", "ipa": "/steɪk/", "chinese": "桩；赌注", "svg": ""},
  {"num": 123, "word": "plain", "ipa": "/pleɪn/", "chinese": "朴素的；平原", "svg": ""},
  {"num": 124, "word": "plane", "ipa": "/pleɪn/", "chinese": "飞机；平面", "svg": ""},
  {"num": 125, "word": "profit", "ipa": "/ˈprɒfɪt/", "chinese": "利润；获益", "svg": ""},
  {"num": 126, "word": "prophet", "ipa": "/ˈprɒfɪt/", "chinese": "先知", "svg": ""},
  {"num": 127, "word": "draught", "ipa": "/drɑːft/", "chinese": "穿堂风；一杯（啤酒）", "svg": ""},
  {"num": 128, "word": "draft", "ipa": "/drɑːft/", "chinese": "草稿；草拟", "svg": ""},
  {"num": 129, "word": "aisle", "ipa": "/aɪl/", "chinese": "通道；走廊", "svg": ""},
  {"num": 130, "word": "isle", "ipa": "/aɪl/", "chinese": "小岛", "svg": ""},
  {"num": 131, "word": "I'll", "ipa": "/aɪl/", "chinese": "我将（I will）", "svg": ""},
  {"num": 132, "word": "sale", "ipa": "/seɪl/", "chinese": "销售；打折", "svg": ""},
  {"num": 133, "word": "sail", "ipa": "/seɪl/", "chinese": "帆；航行", "svg": ""},
  {"num": 134, "word": "tale", "ipa": "/teɪl/", "chinese": "故事；传说", "svg": ""},
  {"num": 135, "word": "tail", "ipa": "/teɪl/", "chinese": "尾巴；尾端", "svg": ""},
  {"num": 136, "word": "morning", "ipa": "/ˈmɔːnɪŋ/", "chinese": "早晨", "svg": ""},
  {"num": 137, "word": "mourning", "ipa": "/ˈmɔːnɪŋ/", "chinese": "哀悼；服丧", "svg": ""},
  {"num": 138, "word": "whole", "ipa": "/həʊl/", "chinese": "整个；全部", "svg": ""},
  {"num": 139, "word": "hole", "ipa": "/həʊl/", "chinese": "洞；孔", "svg": ""},
  {"num": 140, "word": "sole", "ipa": "/səʊl/", "chinese": "唯一的；脚底；鞋底", "svg": ""},
  {"num": 141, "word": "soul", "ipa": "/səʊl/", "chinese": "灵魂", "svg": ""},
  {"num": 142, "word": "role", "ipa": "/rəʊl/", "chinese": "角色；作用", "svg": ""},
  {"num": 143, "word": "roll", "ipa": "/rəʊl/", "chinese": "滚动；卷；面包卷", "svg": ""},
  {"num": 144, "word": "foul", "ipa": "/faʊl/", "chinese": "犯规；恶臭的", "svg": ""},
  {"num": 145, "word": "fowl", "ipa": "/faʊl/", "chinese": "家禽", "svg": ""},
  {"num": 146, "word": "past", "ipa": "/pɑːst/", "chinese": "过去；经过", "svg": ""},
  {"num": 147, "word": "passed", "ipa": "/pɑːst/", "chinese": "通过了（pass的过去式）", "svg": ""},
  {"num": 148, "word": "allowed", "ipa": "/əˈlaʊd/", "chinese": "被允许", "svg": ""},
  {"num": 149, "word": "aloud", "ipa": "/əˈlaʊd/", "chinese": "大声地；出声地", "svg": ""},
  {"num": 150, "word": "cereal", "ipa": "/ˈsɪəriəl/", "chinese": "谷物；麦片", "svg": ""},
  {"num": 151, "word": "serial", "ipa": "/ˈsɪəriəl/", "chinese": "连续的；系列", "svg": ""},
  {"num": 152, "word": "medal", "ipa": "/ˈmedəl/", "chinese": "奖章；勋章", "svg": ""},
  {"num": 153, "word": "meddle", "ipa": "/ˈmedəl/", "chinese": "干涉；多管闲事", "svg": ""},

  {"section": "3. Word-family pronunciation shifts"},
  {"num": 154, "word": "nation", "ipa": "/ˈneɪʃən/", "chinese": "国家", "svg": ""},
  {"num": 155, "word": "national", "ipa": "/ˈnæʃənəl/", "chinese": "国家的；全国的", "svg": ""},
  {"num": 156, "word": "photograph", "ipa": "/ˈfəʊtəɡrɑːf/", "chinese": "照片", "svg": ""},
  {"num": 157, "word": "photographer", "ipa": "/fəˈtɒɡrəfə/", "chinese": "摄影师", "svg": ""},
  {"num": 158, "word": "photography", "ipa": "/fəˈtɒɡrəfi/", "chinese": "摄影（术）", "svg": ""},
  {"num": 159, "word": "reserve", "ipa": "/rɪˈzɜːv/", "chinese": "保留；预订", "svg": ""},
  {"num": 160, "word": "reservoir", "ipa": "/ˈrezəvwɑː/", "chinese": "水库；储蓄", "svg": ""},
  {"num": 161, "word": "sign", "ipa": "/saɪn/", "chinese": "符号；签名", "svg": ""},
  {"num": 162, "word": "signal", "ipa": "/ˈsɪɡnəl/", "chinese": "信号；示意", "svg": ""},
  {"num": 163, "word": "signature", "ipa": "/ˈsɪɡnɪtʃə/", "chinese": "签名；特征", "svg": ""},
  {"num": 164, "word": "electric", "ipa": "/ɪˈlektrɪk/", "chinese": "电的；电动的", "svg": ""},
  {"num": 165, "word": "electricity", "ipa": "/ɪˌlekˈtrɪsɪti/", "chinese": "电；电力", "svg": ""},
  {"num": 166, "word": "electrical", "ipa": "/ɪˈlektrɪkəl/", "chinese": "与电有关的", "svg": ""},
  {"num": 167, "word": "muscle", "ipa": "/ˈmʌsəl/", "chinese": "肌肉", "svg": ""},
  {"num": 168, "word": "muscular", "ipa": "/ˈmʌskjʊlə/", "chinese": "肌肉发达的；强壮的", "svg": ""},
  {"num": 169, "word": "medicine", "ipa": "/ˈmedsɪn/", "chinese": "药；医学", "svg": ""},
  {"num": 170, "word": "medical", "ipa": "/ˈmedɪkəl/", "chinese": "医学的；内科的", "svg": ""},
  {"num": 171, "word": "office", "ipa": "/ˈɒfɪs/", "chinese": "办公室", "svg": ""},
  {"num": 172, "word": "official", "ipa": "/əˈfɪʃəl/", "chinese": "官方的；官员", "svg": ""},
  {"num": 173, "word": "compete", "ipa": "/kəmˈpiːt/", "chinese": "竞争", "svg": ""},
  {"num": 174, "word": "competition", "ipa": "/ˌkɒmpɪˈtɪʃən/", "chinese": "比赛；竞争", "svg": ""},
  {"num": 175, "word": "competitive", "ipa": "/kəmˈpetɪtɪv/", "chinese": "有竞争力的", "svg": ""},
  {"num": 176, "word": "major", "ipa": "/ˈmeɪdʒə/", "chinese": "主要的；大调", "svg": ""},
  {"num": 177, "word": "majority", "ipa": "/məˈdʒɒrɪti/", "chinese": "多数；大多数", "svg": ""},
  {"num": 178, "word": "decide", "ipa": "/dɪˈsaɪd/", "chinese": "决定", "svg": ""},
  {"num": 179, "word": "decision", "ipa": "/dɪˈsɪʒən/", "chinese": "决定；决策", "svg": ""},
  {"num": 180, "word": "decisive", "ipa": "/dɪˈsaɪsɪv/", "chinese": "决定性的；果断的", "svg": ""},
  {"num": 181, "word": "permit", "ipa": "/pəˈmɪt/", "chinese": "允许；许可证", "svg": ""},
  {"num": 182, "word": "permission", "ipa": "/pəˈmɪʃən/", "chinese": "许可；允许", "svg": ""},
  {"num": 183, "word": "permissive", "ipa": "/pəˈmɪsɪv/", "chinese": "开明的；放纵的", "svg": ""},
  {"num": 184, "word": "science", "ipa": "/ˈsaɪəns/", "chinese": "科学", "svg": ""},
  {"num": 185, "word": "scientific", "ipa": "/ˌsaɪənˈtɪfɪk/", "chinese": "科学的", "svg": ""},
  {"num": 186, "word": "economy", "ipa": "/ɪˈkɒnəmi/", "chinese": "经济；节约", "svg": ""},
  {"num": 187, "word": "economic", "ipa": "/ˌiːkəˈnɒmɪk/", "chinese": "经济的；经济学的", "svg": ""},
  {"num": 188, "word": "economical", "ipa": "/ˌiːkəˈnɒmɪkəl/", "chinese": "节省的；经济实惠的", "svg": ""},
  {"num": 189, "word": "politics", "ipa": "/ˈpɒlɪtɪks/", "chinese": "政治", "svg": ""},
  {"num": 190, "word": "political", "ipa": "/pəˈlɪtɪkəl/", "chinese": "政治的", "svg": ""},
  {"num": 191, "word": "politician", "ipa": "/ˌpɒlɪˈtɪʃən/", "chinese": "政客；政治家", "svg": ""},
  {"num": 192, "word": "grammar", "ipa": "/ˈɡræmə/", "chinese": "语法", "svg": ""},
  {"num": 193, "word": "grammatical", "ipa": "/ɡrəˈmætɪkəl/", "chinese": "语法的；合乎语法的", "svg": ""},
  {"num": 194, "word": "broad", "ipa": "/brɔːd/", "chinese": "宽阔的", "svg": ""},
  {"num": 195, "word": "breadth", "ipa": "/bretθ/", "chinese": "宽度；广度", "svg": ""},
  {"num": 196, "word": "long", "ipa": "/lɒŋ/", "chinese": "长的", "svg": ""},
  {"num": 197, "word": "length", "ipa": "/leŋkθ/", "chinese": "长度", "svg": ""},
  {"num": 198, "word": "strong", "ipa": "/strɒŋ/", "chinese": "强壮的", "svg": ""},
  {"num": 199, "word": "strength", "ipa": "/streŋkθ/", "chinese": "力量；优点", "svg": ""},
  {"num": 200, "word": "please", "ipa": "/pliːz/", "chinese": "请；使高兴", "svg": ""},
  {"num": 201, "word": "pleasant", "ipa": "/ˈplezənt/", "chinese": "令人愉快的", "svg": ""},
  {"num": 202, "word": "pleasure", "ipa": "/ˈpleʒə/", "chinese": "乐趣；愉快", "svg": ""},
  {"num": 203, "word": "heal", "ipa": "/hiːl/", "chinese": "治愈；痊愈", "svg": ""},
  {"num": 204, "word": "health", "ipa": "/helθ/", "chinese": "健康", "svg": ""},
  {"num": 205, "word": "healthy", "ipa": "/ˈhelθi/", "chinese": "健康的", "svg": ""},
  {"num": 206, "word": "clean", "ipa": "/kliːn/", "chinese": "干净的", "svg": ""},
  {"num": 207, "word": "cleanse", "ipa": "/klenz/", "chinese": "清洁；净化", "svg": ""},

  {"section": "4. Tricky pronunciation — silent letters & reductions"},
  {"num": 208, "word": "debt", "ipa": "/det/", "chinese": "债务（b不发音）", "svg": ""},
  {"num": 209, "word": "doubt", "ipa": "/daʊt/", "chinese": "怀疑（b不发音）", "svg": ""},
  {"num": 210, "word": "subtle", "ipa": "/ˈsʌtəl/", "chinese": "微妙的（b不发音）", "svg": ""},
  {"num": 211, "word": "thumb", "ipa": "/θʌm/", "chinese": "拇指（b不发音）", "svg": ""},
  {"num": 212, "word": "bomb", "ipa": "/bɒm/", "chinese": "炸弹（b不发音）", "svg": ""},
  {"num": 213, "word": "lamb", "ipa": "/læm/", "chinese": "羔羊（b不发音）", "svg": ""},
  {"num": 214, "word": "knife", "ipa": "/naɪf/", "chinese": "刀（k不发音）", "svg": ""},
  {"num": 215, "word": "knee", "ipa": "/niː/", "chinese": "膝盖（k不发音）", "svg": ""},
  {"num": 216, "word": "knock", "ipa": "/nɒk/", "chinese": "敲门（k不发音）", "svg": ""},
  {"num": 217, "word": "know", "ipa": "/nəʊ/", "chinese": "知道（k不发音）", "svg": ""},
  {"num": 218, "word": "wrap", "ipa": "/ræp/", "chinese": "包裹（w不发音）", "svg": ""},
  {"num": 219, "word": "wrist", "ipa": "/rɪst/", "chinese": "手腕（w不发音）", "svg": ""},
  {"num": 220, "word": "wrong", "ipa": "/rɒŋ/", "chinese": "错误的（w不发音）", "svg": ""},
  {"num": 221, "word": "hour", "ipa": "/aʊə/", "chinese": "小时（h不发音）", "svg": ""},
  {"num": 222, "word": "honest", "ipa": "/ˈɒnɪst/", "chinese": "诚实的（h不发音）", "svg": ""},
  {"num": 223, "word": "heir", "ipa": "/eə/", "chinese": "继承人（h不发音）", "svg": ""},
  {"num": 224, "word": "vehicle", "ipa": "/ˈviːɪkəl/", "chinese": "车辆（h不发音）", "svg": ""},
  {"num": 225, "word": "island", "ipa": "/ˈaɪlənd/", "chinese": "岛屿（s不发音）", "svg": ""},
  {"num": 226, "word": "castle", "ipa": "/ˈkɑːsəl/", "chinese": "城堡（t不发音）", "svg": ""},
  {"num": 227, "word": "fasten", "ipa": "/ˈfɑːsən/", "chinese": "扣紧；系上（t不发音）", "svg": ""},
  {"num": 228, "word": "listen", "ipa": "/ˈlɪsən/", "chinese": "听（t不发音）", "svg": ""},
  {"num": 229, "word": "often", "ipa": "/ˈɒfən/", "chinese": "经常（t通常不发音）", "svg": ""},
  {"num": 230, "word": "glisten", "ipa": "/ˈɡlɪsən/", "chinese": "闪光；发亮（t不发音）", "svg": ""},
  {"num": 231, "word": "mortgage", "ipa": "/ˈmɔːɡɪdʒ/", "chinese": "抵押贷款（t不发音）", "svg": ""},
  {"num": 232, "word": "Wednesday", "ipa": "/ˈwenzdeɪ/", "chinese": "星期三（d不发音）", "svg": ""},
  {"num": 233, "word": "handsome", "ipa": "/ˈhænsəm/", "chinese": "英俊的（d不发音）", "svg": ""},
  {"num": 234, "word": "colonel", "ipa": "/ˈkɜːnəl/", "chinese": "上校（发音如kernel）", "svg": ""},
  {"num": 235, "word": "receipt", "ipa": "/rɪˈsiːt/", "chinese": "收据（p不发音）", "svg": ""},
  {"num": 236, "word": "psychology", "ipa": "/saɪˈkɒlədʒi/", "chinese": "心理学（p不发音）", "svg": ""},
  {"num": 237, "word": "pneumonia", "ipa": "/njuːˈməʊniə/", "chinese": "肺炎（p不发音）", "svg": ""},
  {"num": 238, "word": "sword", "ipa": "/sɔːd/", "chinese": "剑（w不发音）", "svg": ""},
  {"num": 239, "word": "answer", "ipa": "/ˈɑːnsə/", "chinese": "回答（w不发音）", "svg": ""},
  {"num": 240, "word": "chaos", "ipa": "/ˈkeɪɒs/", "chinese": "混乱（ch发/k/音）", "svg": ""},
  {"num": 241, "word": "character", "ipa": "/ˈkærɪktə/", "chinese": "角色；性格（ch发/k/音）", "svg": ""},
  {"num": 242, "word": "stomach", "ipa": "/ˈstʌmək/", "chinese": "胃（ch发/k/音）", "svg": ""},
  {"num": 243, "word": "choir", "ipa": "/ˈkwaɪə/", "chinese": "合唱团（ch发/kw/音）", "svg": ""},
  {"num": 244, "word": "chef", "ipa": "/ʃef/", "chinese": "厨师（ch发/ʃ/音）", "svg": ""},
  {"num": 245, "word": "machine", "ipa": "/məˈʃiːn/", "chinese": "机器（ch发/ʃ/音）", "svg": ""},
  {"num": 246, "word": "brochure", "ipa": "/ˈbrəʊʃə/", "chinese": "小册子（ch发/ʃ/音）", "svg": ""},
  {"num": 247, "word": "queue", "ipa": "/kjuː/", "chinese": "排队（qu发/kj/音）", "svg": ""},
  {"num": 248, "word": "February", "ipa": "/ˈfebruəri/", "chinese": "二月（r常被省略）", "svg": ""},
  {"num": 249, "word": "library", "ipa": "/ˈlaɪbrəri/", "chinese": "图书馆（r常被省略）", "svg": ""},
  {"num": 250, "word": "comfortable", "ipa": "/ˈkʌmftəbəl/", "chinese": "舒适的（or常省略）", "svg": ""},
  {"num": 251, "word": "temperature", "ipa": "/ˈtemprɪtʃə/", "chinese": "温度（era常省略）", "svg": ""},
  {"num": 252, "word": "vegetable", "ipa": "/ˈvedʒtəbəl/", "chinese": "蔬菜（eta常省略）", "svg": ""},
  {"num": 253, "word": "interesting", "ipa": "/ˈɪntrɪstɪŋ/", "chinese": "有趣的（ere常省略）", "svg": ""},
  {"num": 254, "word": "different", "ipa": "/ˈdɪfrənt/", "chinese": "不同的（fe常省略）", "svg": ""},
  {"num": 255, "word": "separate", "ipa": "/ˈseprɪt/", "chinese": "分开的（ara常省略）", "svg": ""},
  {"num": 256, "word": "chocolate", "ipa": "/ˈtʃɒklɪt/", "chinese": "巧克力（ola常省略）", "svg": ""},
  {"num": 257, "word": "business", "ipa": "/ˈbɪznɪs/", "chinese": "生意；商业（i不发音）", "svg": ""},
  {"num": 258, "word": "thorough", "ipa": "/ˈθʌrə/", "chinese": "彻底的（ough发/ə/音）", "svg": ""},
  {"num": 259, "word": "though", "ipa": "/ðəʊ/", "chinese": "虽然（ough发/əʊ/音）", "svg": ""},
  {"num": 260, "word": "through", "ipa": "/θruː/", "chinese": "穿过（ough发/uː/音）", "svg": ""},
  {"num": 261, "word": "cough", "ipa": "/kɒf/", "chinese": "咳嗽（ough发/ɒf/音）", "svg": ""},
  {"num": 262, "word": "enough", "ipa": "/ɪˈnʌf/", "chinese": "足够（ough发/ʌf/音）", "svg": ""},

  {"section": "5. Same spelling, stress changes meaning (noun vs. verb)"},
  {"num": 263, "word": "record (n)", "ipa": "/ˈrekɔːd/", "chinese": "记录；唱片（名词，重音在前）", "svg": ""},
  {"num": 264, "word": "record (v)", "ipa": "/rɪˈkɔːd/", "chinese": "录制；记录（动词，重音在后）", "svg": ""},
  {"num": 265, "word": "present (n/adj)", "ipa": "/ˈprezənt/", "chinese": "礼物；现在的（名词/形容词）", "svg": ""},
  {"num": 266, "word": "present (v)", "ipa": "/prɪˈzent/", "chinese": "展示；呈现（动词）", "svg": ""},
  {"num": 267, "word": "object (n)", "ipa": "/ˈɒbdʒɪkt/", "chinese": "物体；目标（名词）", "svg": ""},
  {"num": 268, "word": "object (v)", "ipa": "/əbˈdʒekt/", "chinese": "反对；异议（动词）", "svg": ""},
  {"num": 269, "word": "permit (n)", "ipa": "/ˈpɜːmɪt/", "chinese": "许可证（名词）", "svg": ""},
  {"num": 270, "word": "permit (v)", "ipa": "/pəˈmɪt/", "chinese": "允许（动词）", "svg": ""},
  {"num": 271, "word": "protest (n)", "ipa": "/ˈprəʊtest/", "chinese": "抗议（名词）", "svg": ""},
  {"num": 272, "word": "protest (v)", "ipa": "/prəˈtest/", "chinese": "抗议；表示反对（动词）", "svg": ""},
  {"num": 273, "word": "contract (n)", "ipa": "/ˈkɒntrækt/", "chinese": "合同（名词）", "svg": ""},
  {"num": 274, "word": "contract (v)", "ipa": "/kənˈtrækt/", "chinese": "收缩；感染（动词）", "svg": ""},
  {"num": 275, "word": "convict (n)", "ipa": "/ˈkɒnvɪkt/", "chinese": "罪犯（名词）", "svg": ""},
  {"num": 276, "word": "convict (v)", "ipa": "/kənˈvɪkt/", "chinese": "定罪（动词）", "svg": ""},
  {"num": 277, "word": "conduct (n)", "ipa": "/ˈkɒndʌkt/", "chinese": "行为；品行（名词）", "svg": ""},
  {"num": 278, "word": "conduct (v)", "ipa": "/kənˈdʌkt/", "chinese": "指挥；执行（动词）", "svg": ""},
  {"num": 279, "word": "conflict (n)", "ipa": "/ˈkɒnflɪkt/", "chinese": "冲突（名词）", "svg": ""},
  {"num": 280, "word": "conflict (v)", "ipa": "/kənˈflɪkt/", "chinese": "冲突；矛盾（动词）", "svg": ""},
  {"num": 281, "word": "content (n/adj)", "ipa": "/ˈkɒntent/", "chinese": "内容；满足的（名词/形容词）", "svg": ""},
  {"num": 282, "word": "content (v)", "ipa": "/kənˈtent/", "chinese": "使满足（动词）", "svg": ""},
  {"num": 283, "word": "export (n)", "ipa": "/ˈekspɔːt/", "chinese": "出口品（名词）", "svg": ""},
  {"num": 284, "word": "export (v)", "ipa": "/ɪkˈspɔːt/", "chinese": "出口（动词）", "svg": ""},
  {"num": 285, "word": "import (n)", "ipa": "/ˈɪmpɔːt/", "chinese": "进口品（名词）", "svg": ""},
  {"num": 286, "word": "import (v)", "ipa": "/ɪmˈpɔːt/", "chinese": "进口（动词）", "svg": ""},
  {"num": 287, "word": "increase (n)", "ipa": "/ˈɪŋkriːs/", "chinese": "增加（名词）", "svg": ""},
  {"num": 288, "word": "increase (v)", "ipa": "/ɪŋˈkriːs/", "chinese": "增加（动词）", "svg": ""},
  {"num": 289, "word": "decrease (n)", "ipa": "/ˈdiːkriːs/", "chinese": "减少（名词）", "svg": ""},
  {"num": 290, "word": "decrease (v)", "ipa": "/dɪˈkriːs/", "chinese": "减少（动词）", "svg": ""},
  {"num": 291, "word": "refund (n)", "ipa": "/ˈriːfʌnd/", "chinese": "退款（名词）", "svg": ""},
  {"num": 292, "word": "refund (v)", "ipa": "/rɪˈfʌnd/", "chinese": "退款（动词）", "svg": ""},

  {"section": "6. Heteronyms — same spelling, different sound & meaning"},
  {"num": 293, "word": "read (present)", "ipa": "/riːd/", "chinese": "读（现在式）", "svg": ""},
  {"num": 294, "word": "read (past)", "ipa": "/red/", "chinese": "读了（过去式）", "svg": ""},
  {"num": 295, "word": "live (v)", "ipa": "/lɪv/", "chinese": "居住；活着（动词）", "svg": ""},
  {"num": 296, "word": "live (adj)", "ipa": "/laɪv/", "chinese": "现场的；活的（形容词）", "svg": ""},
  {"num": 297, "word": "wind (n)", "ipa": "/wɪnd/", "chinese": "风（名词）", "svg": ""},
  {"num": 298, "word": "wind (v)", "ipa": "/waɪnd/", "chinese": "绕；缠绕（动词）", "svg": ""},
  {"num": 299, "word": "tear (n, eye)", "ipa": "/tɪə/", "chinese": "眼泪（名词）", "svg": ""},
  {"num": 300, "word": "tear (v, rip)", "ipa": "/teə/", "chinese": "撕裂（动词）", "svg": ""},
  {"num": 301, "word": "lead (v)", "ipa": "/liːd/", "chinese": "领导；带路（动词）", "svg": ""},
  {"num": 302, "word": "lead (n, metal)", "ipa": "/led/", "chinese": "铅（金属名词）", "svg": ""},
  {"num": 303, "word": "bow (front of ship)", "ipa": "/baʊ/", "chinese": "船头；鞠躬", "svg": ""},
  {"num": 304, "word": "bow (ribbon / weapon)", "ipa": "/bəʊ/", "chinese": "蝴蝶结；弓", "svg": ""},
  {"num": 305, "word": "row (argument)", "ipa": "/raʊ/", "chinese": "争吵；吵架", "svg": ""},
  {"num": 306, "word": "row (line / to paddle)", "ipa": "/rəʊ/", "chinese": "排；划船", "svg": ""},
  {"num": 307, "word": "wound (n/v, injury)", "ipa": "/wuːnd/", "chinese": "伤口；使受伤", "svg": ""},
  {"num": 308, "word": "wound (past of wind)", "ipa": "/waʊnd/", "chinese": "wind的过去式（缠绕）", "svg": ""},
  {"num": 309, "word": "sow (v, plant seeds)", "ipa": "/səʊ/", "chinese": "播种（动词）", "svg": ""},
  {"num": 310, "word": "sow (n, female pig)", "ipa": "/saʊ/", "chinese": "母猪（名词）", "svg": ""}
]}

with open(r'C:\Apps\vocab-cards\data\confusables.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print('Done:', len(data['words']), 'total entries')
